add_test([=[UnitaryTest.MeshTest]=]  /home/nxirda/Desktop/POO_CS/Projet_Simulation/release/Test [==[--gtest_filter=UnitaryTest.MeshTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UnitaryTest.MeshTest]=]  PROPERTIES WORKING_DIRECTORY /home/nxirda/Desktop/POO_CS/Projet_Simulation/release SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UnitaryTest.ProblemTest]=]  /home/nxirda/Desktop/POO_CS/Projet_Simulation/release/Test [==[--gtest_filter=UnitaryTest.ProblemTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UnitaryTest.ProblemTest]=]  PROPERTIES WORKING_DIRECTORY /home/nxirda/Desktop/POO_CS/Projet_Simulation/release SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[UnitaryTest.EquationTest]=]  /home/nxirda/Desktop/POO_CS/Projet_Simulation/release/Test [==[--gtest_filter=UnitaryTest.EquationTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[UnitaryTest.EquationTest]=]  PROPERTIES WORKING_DIRECTORY /home/nxirda/Desktop/POO_CS/Projet_Simulation/release SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MainFunctionTest.EquationTest]=]  /home/nxirda/Desktop/POO_CS/Projet_Simulation/release/Test [==[--gtest_filter=MainFunctionTest.EquationTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MainFunctionTest.EquationTest]=]  PROPERTIES WORKING_DIRECTORY /home/nxirda/Desktop/POO_CS/Projet_Simulation/release SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  Test_TESTS UnitaryTest.MeshTest UnitaryTest.ProblemTest UnitaryTest.EquationTest MainFunctionTest.EquationTest)
